<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class TaxesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('taxes')->insert([
            ['code' => '303', 'conception' => 'Honorarios profesionales y demás pagos por servicios relacionados con el título profesional', 'porcentage' => 10, 'type' => 'renta'],
            ['code' => '304', 'conception' => 'Servicios predomina el intelecto no relacionados con el título profesional', 'porcentage' => 8, 'type' => 'renta'],
            ['code' => '304A', 'conception' => 'Comisiones y demás pagos por servicios predomina intelecto no relacionados con el título profesional', 'porcentage' => 8, 'type' => 'renta'],
            ['code' => '304B', 'conception' => 'Pagos a notarios y registradores de la propiedad y mercantil por sus actividades ejercidas como tales', 'porcentage' => 8, 'type' => 'renta'],
            ['code' => '304C', 'conception' => 'Pagos a deportistas, entrenadores, árbitros, miembros del cuerpo técnico por sus actividades ejercidas como tales', 'porcentage' => 8, 'type' => 'renta'],
            ['code' => '304D', 'conception' => 'Pagos a artistas por sus actividades ejercidas como tales', 'porcentage' => 8, 'type' => 'renta'],
            ['code' => '304E', 'conception' => 'Honorarios y demás pagos por servicios de docencia', 'porcentage' => 8, 'type' => 'renta'],
            ['code' => '307', 'conception' => 'Servicios predomina la mano de obra', 'porcentage' => 2, 'type' => 'renta'],
            ['code' => '308', 'conception' => 'Utilización o aprovechamiento de la imagen o renombre', 'porcentage' => 10, 'type' => 'renta'],
            ['code' => '309', 'conception' => 'Servicios prestados por medios de comunicación y agencias de publicidad', 'porcentage' => 1.75, 'type' => 'renta'],
            ['code' => '310', 'conception' => 'Servicio de transporte privado de pasajeros o transporte público o privado de carga', 'porcentage' => 1, 'type' => 'renta'],
            ['code' => '311', 'conception' => 'Pagos a través de liquidación de compra (nivel cultural o rusticidad)', 'porcentage' => 2, 'type' => 'renta'],
            ['code' => '312', 'conception' => 'Transferencia de bienes muebles de naturaleza corporal', 'porcentage' => 1.75, 'type' => 'renta'],
            ['code' => '312A', 'conception' => 'Compra de bienes de origen agrícola, avícola, pecuario, apícola, cunícula, bioacuático, forestal y carnes en estado natural', 'porcentage' => 1, 'type' => 'renta'],
            ['code' => '312B', 'conception' => 'Impuesto a la Renta único para la actividad de producción y cultivo de palma aceitera', 'porcentage' => 1, 'type' => 'renta'],
            ['code' => '314A', 'conception' => 'Regalías por concepto de franquicias de acuerdo a Ley de Propiedad Intelectual - pago a personas naturales', 'porcentage' => 8, 'type' => 'renta'],
            ['code' => '314B', 'conception' => 'Cánones, derechos de autor,  marcas, patentes y similares de acuerdo a Ley de Propiedad Intelectual – pago a personas naturales', 'porcentage' => 8, 'type' => 'renta'],
            ['code' => '314C', 'conception' => 'Regalías por concepto de franquicias de acuerdo a Ley de Propiedad Intelectual  - pago a sociedades', 'porcentage' => 8, 'type' => 'renta'],
            ['code' => '314D', 'conception' => 'Cánones, derechos de autor,  marcas, patentes y similares de acuerdo a Ley de Propiedad Intelectual – pago a sociedades', 'porcentage' => 8, 'type' => 'renta'],
            ['code' => '319', 'conception' => 'Cuotas de arrendamiento mercantil (prestado por sociedades), inclusive la de opción de compra', 'porcentage' => 1.75, 'type' => 'renta'],
            ['code' => '320', 'conception' => 'Arrendamiento bienes inmuebles', 'porcentage' => 8, 'type' => 'renta'],
            ['code' => '322', 'conception' => 'Seguros y reaseguros (primas y cesiones)', 'porcentage' => 1.75, 'type' => 'renta'],
            ['code' => '323', 'conception' => 'Rendimientos financieros pagados a naturales y sociedades (No a IFIs)', 'porcentage' => 2, 'type' => 'renta'],
            ['code' => '323A', 'conception' => 'Rendimientos financieros depósitos Cta. Corriente', 'porcentage' => 2, 'type' => 'renta'],
            ['code' => '323B1', 'conception' => 'Rendimientos financieros  depósitos Cta. Ahorros Sociedades', 'porcentage' => 2, 'type' => 'renta'],
            ['code' => '323E', 'conception' => 'Rendimientos financieros depósito a plazo fijo gravados', 'porcentage' => 2, 'type' => 'renta'],
            ['code' => '323E2', 'conception' => 'Rendimientos financieros depósito a plazo fijo exentos', 'porcentage' => 0, 'type' => 'renta'],
            ['code' => '323F', 'conception' => 'Rendimientos financieros operaciones de reporto - repos', 'porcentage' => 2, 'type' => 'renta'],
            ['code' => '323G', 'conception' => 'Inversiones (captaciones) rendimientos distintos de aquellos pagados a IFIs', 'porcentage' => 2, 'type' => 'renta'],
            ['code' => '323H', 'conception' => 'Rendimientos financieros  obligaciones', 'porcentage' => 2, 'type' => 'renta'],
            ['code' => '323I', 'conception' => 'Rendimientos financieros  bonos convertible en acciones', 'porcentage' => 2, 'type' => 'renta'],
            ['code' => '323 M', 'conception' => 'Rendimientos financieros : Inversiones en títulos valores en renta fija gravados', 'porcentage' => 2, 'type' => 'renta'],
            ['code' => '323 N', 'conception' => 'Rendimientos financieros  Inversiones en títulos valores en renta fija exentos', 'porcentage' => 0, 'type' => 'renta'],
            ['code' => '323 O', 'conception' => 'Intereses y demás rendimientos financieros pagados a bancos y otras entidades sometidas al control de la Superintendencia de Bancos y de la Economía Popular y Solidaria', 'porcentage' => 0, 'type' => 'renta'],
            ['code' => '323 P', 'conception' => 'Intereses pagados por entidades del sector público a favor de sujetos pasivos', 'porcentage' => 2, 'type' => 'renta'],
            ['code' => '323Q', 'conception' => 'Otros intereses y rendimientos financieros gravados ', 'porcentage' => 2, 'type' => 'renta'],
            ['code' => '323R', 'conception' => 'Otros intereses y rendimientos financieros exentos', 'porcentage' => 0, 'type' => 'renta'],
            ['code' => '323S', 'conception' => 'Pagos y créditos en cuenta efectuados por el BCE y los depósitos centralizados de valores, en calidad de intermediarios, a instituciones del sistema financiero por cuenta de otras personas naturales y sociedades', 'porcentage' => 2, 'type' => 'renta'],
            ['code' => '323T', 'conception' => 'Rendimientos financieros originados en la deuda pública ecuatoriana', 'porcentage' => 0, 'type' => 'renta'],
            ['code' => '323U', 'conception' => 'Rendimientos financieros originados en títulos valores de obligaciones de 360 días o más para el financiamiento de proyectos públicos en asociación público-privada', 'porcentage' => 0, 'type' => 'renta'],
            ['code' => '324A', 'conception' => 'Intereses en operaciones de crédito entre instituciones del sistema financiero y entidades economía popular y solidaria', 'porcentage' => 1, 'type' => 'renta'],
            ['code' => '324B', 'conception' => 'Inversiones entre instituciones del sistema financiero y entidades economía popular y solidaria', 'porcentage' => 1, 'type' => 'renta'],
            ['code' => '324C', 'conception' => 'Pagos y créditos en cuenta efectuados por el BCE y los depósitos centralizados de valores, en calidad de intermediarios, a instituciones del sistema financiero por cuenta de otras instituciones del sistema financiero', 'porcentage' => 1, 'type' => 'renta'],
            ['code' => '325', 'conception' => 'Anticipo dividendos', 'porcentage' => NULL, 'type' => 'renta'],
            ['code' => '325A', 'conception' => 'Préstamos accionistas, beneficiarios o partícipes residentes o establecidos en el Ecuador', 'porcentage' => NULL, 'type' => 'renta'],
            ['code' => '326', 'conception' => 'Dividendos distribuidos que correspondan al impuesto a la renta único establecido en el art. 27 de la LRTI', 'porcentage' => NULL, 'type' => 'renta'],
            ['code' => '327', 'conception' => 'Dividendos distribuidos a personas naturales residentes', 'porcentage' => NULL, 'type' => 'renta'],
            ['code' => '328', 'conception' => 'Dividendos distribuidos a sociedades residentes', 'porcentage' => 0, 'type' => 'renta'],
            ['code' => '329', 'conception' => 'dividendos distribuidos a fideicomisos residentes', 'porcentage' => 0, 'type' => 'renta'],
            ['code' => '331', 'conception' => 'Dividendos en acciones (capitalización de utilidades)', 'porcentage' => 0, 'type' => 'renta'],
            ['code' => '332', 'conception' => 'Otras compras de bienes y servicios no sujetas a retención', 'porcentage' => 0, 'type' => 'renta'],
            ['code' => '332B', 'conception' => 'Compra de bienes inmuebles', 'porcentage' => 0, 'type' => 'renta'],
            ['code' => '332C', 'conception' => 'Transporte público de pasajeros', 'porcentage' => 0, 'type' => 'renta'],
            ['code' => '332D', 'conception' => 'Pagos en el país por transporte de pasajeros o transporte internacional de carga, a compañías nacionales o extranjeras de aviación o marítimas', 'porcentage' => 0, 'type' => 'renta'],
            ['code' => '332E', 'conception' => 'Valores entregados por las cooperativas de transporte a sus socios', 'porcentage' => 0, 'type' => 'renta'],
            ['code' => '332F', 'conception' => 'Compraventa de divisas distintas al dólar de los Estados Unidos de América', 'porcentage' => 0, 'type' => 'renta'],
            ['code' => '332G', 'conception' => 'Pagos con tarjeta de crédito', 'porcentage' => 0, 'type' => 'renta'],
            ['code' => '332H', 'conception' => 'Pago al exterior tarjeta de crédito reportada por la Emisora de tarjeta de crédito, solo recap', 'porcentage' => 0, 'type' => 'renta'],
            ['code' => '332I', 'conception' => 'Pago a través de convenio de debito (Clientes IFI`s)', 'porcentage' => 0, 'type' => 'renta'],
            ['code' => '333', 'conception' => 'Ganancia en la enajenación de derechos representativos de capital u otros derechos que permitan la exploración, explotación, concesión o similares de sociedades, que se coticen en bolsa de valores del Ecuador', 'porcentage' => 10, 'type' => 'renta'],
            ['code' => '334', 'conception' => 'Contraprestación producida por la enajenación de derechos representativos de capital u otros derechos que permitan la exploración, explotación, concesión o similares de sociedades, no cotizados en bolsa de valores del Ecuador', 'porcentage' => 1, 'type' => 'renta'],
            ['code' => '335', 'conception' => 'Loterías, rifas, apuestas y similares', 'porcentage' => 15, 'type' => 'renta'],
            ['code' => '336', 'conception' => 'Venta de combustibles a comercializadoras', 'porcentage' => NULL, 'type' => 'renta'],
            ['code' => '337', 'conception' => 'Venta de combustibles a distribuidores', 'porcentage' => NULL, 'type' => 'renta'],
            ['code' => '338', 'conception' => 'Producción y venta local de banano producido o no por el mismo sujeto pasivo', 'porcentage' => NULL, 'type' => 'renta'],
            ['code' => '340', 'conception' => 'Impuesto único a la exportación de banano', 'porcentage' => 3, 'type' => 'renta'],
            ['code' => '343', 'conception' => 'Otras retenciones aplicables el 1%', 'porcentage' => 1, 'type' => 'renta'],
            ['code' => '343A', 'conception' => 'Energía eléctrica', 'porcentage' => 1, 'type' => 'renta'],
            ['code' => '343B', 'conception' => 'Actividades de construcción de obra material inmueble, urbanización, lotización o actividades similares', 'porcentage' => 1.75, 'type' => 'renta'],
            ['code' => '343C', 'conception' => 'Impuesto Redimible a las botellas plásticas - IRBP', 'porcentage' => 1, 'type' => 'renta'],
            ['code' => '3440', 'conception' => 'Otras retenciones aplicables el 2,75%', 'porcentage' => 2.75, 'type' => 'renta'],
            ['code' => '344A', 'conception' => 'Pago local tarjeta de crédito / débito reportada por la Emisora de tarjeta de crédito / entidades del sistema financiero', 'porcentage' => 2, 'type' => 'renta'],
            ['code' => '344B', 'conception' => 'Adquisición de sustancias minerales dentro del territorio nacional', 'porcentage' => 2, 'type' => 'renta'],
            ['code' => '345', 'conception' => 'Otras retenciones aplicables el 8%', 'porcentage' => 8, 'type' => 'renta'],
            ['code' => '346', 'conception' => 'Otras retenciones aplicables a otros porcentajes (incluye regimen Microempresarial)', 'porcentage' => NULL, 'type' => 'renta'],
            ['code' => '346A', 'conception' => 'Otras ganancias de capital distintas de enajenación de derechos representativos de capital ', 'porcentage' => NULL, 'type' => 'renta'],
            ['code' => '346B', 'conception' => 'Donaciones en dinero -Impuesto a la donaciones ', 'porcentage' => NULL, 'type' => 'renta'],
            ['code' => '346C', 'conception' => 'Retención a cargo del propio sujeto pasivo por la exportación de concentrados y/o elementos metálicos', 'porcentage' => NULL, 'type' => 'renta'],
            ['code' => '346D', 'conception' => 'Retención a cargo del propio sujeto pasivo por la comercialización de productos forestales', 'porcentage' => NULL, 'type' => 'renta'],
            ['code' => '348', 'conception' => 'Impuesto único a ingresos provenientes de actividades agropecuarias en etapa de producción / comercialización local o exportación', 'porcentage' => 1, 'type' => 'renta'],
            ['code' => '350', 'conception' => 'Otras autoretenciones', 'porcentage' => NULL, 'type' => 'renta'],
            ['code' => '500', 'conception' => 'Pago a no residentes - Rentas Inmobiliarias', 'porcentage' => NULL, 'type' => 'renta'],
            ['code' => '501', 'conception' => 'Pago a no residentes - Beneficios/Servicios  Empresariales', 'porcentage' => NULL, 'type' => 'renta'],
            ['code' => '501A', 'conception' => 'Pago a no residentes - Servicios técnicos, administrativos o de consultoría y regalías', 'porcentage' => NULL, 'type' => 'renta'],
            ['code' => '503', 'conception' => 'Pago a no residentes- Navegación Marítima y/o aérea', 'porcentage' => NULL, 'type' => 'renta'],
            ['code' => '504', 'conception' => 'Pago a no residentes- Dividendos distribuidos a personas naturales (domicilados o no en paraiso fiscal) o a sociedades sin beneficiario efectivo persona natural residente en Ecuador', 'porcentage' => 25, 'type' => 'renta'],
            ['code' => '504A', 'conception' => 'Dividendos a sociedades con beneficiario efectivo persona natural residente en el Ecuador', 'porcentage' => NULL, 'type' => 'renta'],
            ['code' => '504B', 'conception' => 'Dividendos a no residentes incumpliendo el deber de informar la composición societaria', 'porcentage' => 35, 'type' => 'renta'],
            ['code' => '504C', 'conception' => 'Dividendos a residentes o establecidos en paraísos fiscales o regímenes de menor imposición (con beneficiario Persona Natural residente en Ecuador)', 'porcentage' => NULL, 'type' => 'renta'],
            ['code' => '504D', 'conception' => 'Dividendos a fideicomisos o establecidos en paraísos fiscales o regímenes de menor imposición (con beneficiario Persona Natural residente en Ecuador)', 'porcentage' => NULL, 'type' => 'renta'],
            ['code' => '504E', 'conception' => 'Pago a no residentes - Anticipo dividendos (no domiciliada en paraísos fiscales o regímenes de menor imposición)', 'porcentage' => NULL, 'type' => 'renta'],
            ['code' => '504F', 'conception' => 'Pago a no residentes - Anticipo dividendos (domiciliadas en paraísos fiscales o regímenes de menor imposición)', 'porcentage' => NULL, 'type' => 'renta'],
            ['code' => '504G', 'conception' => 'Pago a no residentes - Préstamos accionistas, beneficiarios o partìcipes (no domiciladas en paraísos fiscales o regímenes de menor imposición)', 'porcentage' => NULL, 'type' => 'renta'],
            ['code' => '504H', 'conception' => 'Pago a no residentes - Préstamos accionistas, beneficiarios o partìcipes (domiciladas en paraísos fiscales o regímenes de menor imposición)', 'porcentage' => NULL, 'type' => 'renta'],
            ['code' => '504I', 'conception' => 'Pago a no residentes - Préstamos no comerciales a partes relacionadas  (no domiciladas en paraísos fiscales o regímenes de menor imposición)', 'porcentage' => NULL, 'type' => 'renta'],
            ['code' => '504J', 'conception' => 'Pago a no residentes - Préstamos no comerciales a partes relacionadas  (domiciladas en paraísos fiscales o regímenes de menor imposición)', 'porcentage' => NULL, 'type' => 'renta'],
            ['code' => '505', 'conception' => 'Pago a no residentes - Rendimientos financieros', 'porcentage' => NULL, 'type' => 'renta'],
            ['code' => '505A', 'conception' => 'Pago a no residentes – Intereses de créditos de Instituciones Financieras del exterior', 'porcentage' => NULL, 'type' => 'renta'],
            ['code' => '505B', 'conception' => 'Pago a no residentes – Intereses de créditos de gobierno a gobierno', 'porcentage' => NULL, 'type' => 'renta'],
            ['code' => '505C', 'conception' => 'Pago a no residentes – Intereses de créditos de organismos multilaterales', 'porcentage' => NULL, 'type' => 'renta'],
            ['code' => '505D', 'conception' => 'Pago a no residentes - Intereses por financiamiento de proveedores externos', 'porcentage' => 25, 'type' => 'renta'],
            ['code' => '505E', 'conception' => 'Pago a no residentes - Intereses de otros créditos externos', 'porcentage' => 25, 'type' => 'renta'],
            ['code' => '505F', 'conception' => 'Pago a no residentes - Otros Intereses y Rendimientos Financieros', 'porcentage' => NULL, 'type' => 'renta'],
            ['code' => '509', 'conception' => 'Pago a no residentes- Cánones, derechos de autor,  marcas, patentes y similares', 'porcentage' => NULL, 'type' => 'renta'],
            ['code' => '509A', 'conception' => 'PPago a no residentes - Regalías por concepto de franquicias', 'porcentage' => NULL, 'type' => 'renta'],
            ['code' => '510', 'conception' => 'Pago a no residentes - Otras ganancias de capital distintas de enajenación de derechos representativos de capital', 'porcentage' => NULL, 'type' => 'renta'],
            ['code' => '511', 'conception' => 'Pago a no residentes - Servicios profesionales independientes', 'porcentage' => NULL, 'type' => 'renta'],
            ['code' => '512', 'conception' => 'Pago a no residentes - Servicios profesionales dependientes', 'porcentage' => NULL, 'type' => 'renta'],
            ['code' => '513', 'conception' => 'Pago a no residentes- Artistas', 'porcentage' => NULL, 'type' => 'renta'],
            ['code' => '513A', 'conception' => 'Pago a no residentes - Deportistas', 'porcentage' => NULL, 'type' => 'renta'],
            ['code' => '514', 'conception' => 'Pago a no residentes - Participación de consejeros', 'porcentage' => NULL, 'type' => 'renta'],
            ['code' => '515', 'conception' => 'Pago a no residentes - Entretenimiento Público', 'porcentage' => NULL, 'type' => 'renta'],
            ['code' => '516', 'conception' => 'Pago a no residentes - Pensiones', 'porcentage' => NULL, 'type' => 'renta'],
            ['code' => '517', 'conception' => 'Pago a no residentes- Reembolso de Gastos', 'porcentage' => NULL, 'type' => 'renta'],
            ['code' => '518', 'conception' => 'Pago a no residentes- Funciones Públicas', 'porcentage' => NULL, 'type' => 'renta'],
            ['code' => '519', 'conception' => 'Pago a no residentes - Estudiantes', 'porcentage' => NULL, 'type' => 'renta'],
            ['code' => '520A', 'conception' => 'Pago a no residentes - Pago a proveedores de servicios hoteleros y turísticos en el exterior', 'porcentage' => NULL, 'type' => 'renta'],
            ['code' => '520B', 'conception' => 'Pago a no residentes - Arrendamientos mercantil internacional', 'porcentage' => NULL, 'type' => 'renta'],
            ['code' => '520D', 'conception' => 'Pago a no residentes - Comisiones por exportaciones y por promoción de turismo receptivo', 'porcentage' => NULL, 'type' => 'renta'],
            ['code' => '520E', 'conception' => 'Pago a no residentes - Por las empresas de transporte marítimo o aéreo y por empresas pesqueras de alta mar, por su actividad.', 'porcentage' => 0, 'type' => 'renta'],
            ['code' => '520F', 'conception' => 'Pago a no residentes - Por las agencias internacionales de prensa', 'porcentage' => NULL, 'type' => 'renta'],
            ['code' => '520G', 'conception' => 'Pago a no residentes - Contratos de fletamento de naves para empresas de transporte aéreo o marítimo internacional', 'porcentage' => NULL, 'type' => 'renta'],
            ['code' => '521', 'conception' => 'Pago a no residentes - Enajenación de derechos representativos de capital u otros derechos que permitan la exploración, explotación, concesión o similares de sociedades', 'porcentage' => NULL, 'type' => 'renta'],
            ['code' => '523A', 'conception' => 'Pago a no residentes - Seguros y reaseguros (primas y cesiones)', 'porcentage' => NULL, 'type' => 'renta'],
            ['code' => '525', 'conception' => 'Pago a no residentes- Donaciones en dinero -Impuesto a la donaciones', 'porcentage' => NULL, 'type' => 'renta'],

            ['code' => '9', 'conception' => '10', 'porcentage' => 10, 'type' => 'iva'],
            ['code' => '10', 'conception' => '20', 'porcentage' => 20, 'type' => 'iva'],
            ['code' => '1', 'conception' => '30', 'porcentage' => 30, 'type' => 'iva'],
            ['code' => '11', 'conception' => '50', 'porcentage' => 50, 'type' => 'iva'],
            ['code' => '2', 'conception' => '70', 'porcentage' => 70, 'type' => 'iva'],
            ['code' => '3', 'conception' => '100', 'porcentage' => 100, 'type' => 'iva']
        ]);
    }
}
