version: '3.8'

services:
  app:
    build:
      args:
        user: sammy
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: lumen-app
    working_dir: /var/www/
    container_name: lumen_app
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    volumes:
      - ./:/var/www
    networks:
      - lumen-network

  mysql:
    image: mysql:5.7
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - "3306:3306"
    networks:
      - lumen-network
    platform: linux/amd64  # Important for M1 compatibility
    volumes:
      - my-datavolume:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: ${DB_USERNAME}
      PMA_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8080:80"
    networks:
      - lumen-network

  nginx:
    image: nginx:alpine
    ports:
      - 8005:80
    depends_on:
      - mysql
      - app
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - lumen-network
      
networks:
  lumen-network:
    driver: bridge

volumes:
  my-datavolume:
    driver: local
